### ISSUE TITLE
Coherence for number_of_days indicators.

### ISSUE THREAD

**Issue by aulemahal** [clix-meta/clix-meta#23]
# Please explain briefly what is wrong

Hi again. Follow up to the discussion about units of indicators with a "number_of_days_\*"  standard name. At xclim, we decided to comply to the CF conventions, even if we don't really like this dimensionless thing. However, I see some inconsistencies in the index definition table. I believe all of these indicators have standard names absent from the current official table, but I think it would be more coherent if all "number_of_days_\*" indicators were dimensionless.

# Suggest specific changes to the `index_definition` table

 
| *Column name* | *Present (wrong) entry* | *Suggested correction* |
| ------ | ------ | ------ |
| VarName | sd1, sd5cm, sd50cm, sd{D}cm |  |
| OUTPUT_units | day | 1 |

Similarly:

| *Column name* | *Present (wrong) entry* | *Suggested correction* |
| ------ | ------ | ------ |
| VarName | nzero |  |
| OUTPUT_units | ?????? | 1 |

**Comment by zklaus** [comment]
See also comments [here](https://github.com/clix-meta/clix-meta/issues/20#issuecomment-824248199), [here](https://github.com/clix-meta/clix-meta/issues/20#issuecomment-824263991), and [here](https://github.com/clix-meta/clix-meta/issues/20#issuecomment-825098439).

**Comment by larsbarring** [comment]
Thanks for pointing out these mistakes. Update is now on its way.

**Comment by larsbarring** [comment]
Now implemented in master branch.
