### ISSUE TITLE
Clarify the role of placeholders

### ISSUE THREAD

**Issue by zklaus** [clix-meta/clix-meta#30]
In several issues, the placeholder mechanism has surfaced in various ways. Here, we collect those issues and try to clarify the placeholders mechanism.

Issues: #25, #26

**Comment by zklaus** [comment]
We should improve the documentation of placeholder, for example it should be stated that we only intend them to take integer values and that `-10` is encoded as `m10`.

**Comment by larsbarring** [comment]
Yes, I agree, but I am not sure where to put such information. Suggestions?

In the README sheet of the `master_table.xls` file the following note appears:

> NOTE: In several columns the construct {TT}, or similar, appears. This is a placeholder for the threshold value (only integers,  decimal values are not allowed). For negative values the minus sign has to be replaced by a lowercase m. For example, for the threshold value -4 "{TT}" has to be written as “m4”,  and the output variable name thus becomes "tngtm4". The situation of having multiple thresholds is not yet covered.

**Comment by larsbarring** [comment]
Now closing this. Reopen additional ideas come to mind.
