### ISSUE TITLE
hd17 is deficit (not excess as it is now)

### ISSUE THREAD

**Issue by larsbarring** [clix-meta/clix-meta#49]
# Please explain briefly what is wrong
Heating degree-days is the (positive) sum of temperature values below the threshold, i.e. a deficit not an excess

# Suggest specific changes to the `index_definition` table

 
| *Column name* | *Present (wrong) entry* | *Suggested correction* |
| ------ | ------ | ------ |
| VarName |  |  |
| Input |  |  |
| OUTPUT_standard_name| integral_of_air_temperature_excess_wrt_time | integral_wrt_time_of_air_temperature_deficit |
| OUTPUT_cell_methods |  |  |
| OUTPUT_units |  |  |
| OUTPUT_proposed_standard_name |  |  |
| OUTPUT_proposed_cell_methods |  |  |
| OUTPUT_proposed_units |  |  |
| OUTPUT_long_name | .... (sum of Tmean > 17 C) | .... (sum of Tmean < 17 C) |
| OUTPUT_reference |  |  |
| allowed_freq |  |  |
| default_freq |  |  |
| index_function |  |  |
| N_parameters |  |  |
| parameter_name | | |
| PARAMETER_definition | .... condition: >  | .... condition: < |
| ET_short_name |  |  |
| ET_long_name |  |  |
| ET_definition |  |  |
| ET_comment |  |  |

**Comment by zklaus** [comment]
I was not able to find the mentioned standard names in [the CF Conventions Standard Name Table](http://cfconventions.org/Data/cf-standard-names/77/build/cf-standard-name-table.html). Could you perhaps spell them out? Or should that be in `proposed_standard_name`?

**Comment by larsbarring** [comment]
Quite right, the standard name`integral_of_air_temperature_excess_wrt_time` has been deprecated. The correct table line (above) is:



Column name | Present (wrong) entry | Suggested correction. 
-- | -- | --
OUTPUT_standard_name | integral_of_air_temperature_excess_wrt_time | integral_wrt_time_of_air_temperature_deficit

**Comment by zklaus** [comment]
Ah yes, with this I found it, however, I think it is `integral_wrt_time_of_air_temperature_excess` (and `deficit`), i.e. the `wrt_time` follows immediately after integral. I will edit the issue description to reflect this; please correct me if I am wrong.

**Comment by zklaus** [comment]
The order seems to have been changed in version 48 of the standard names table. Should we update all similar standard names (in a new issue, of course)?

**Comment by larsbarring** [comment]
cf #50
